app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

get('/', 'DashboardController@getIndex');

//Restful controllers
Route::controller('dashboard', 'DashboardController');
Route::controller('systems', 'SystemController');
Route::controller('games', 'GameController');
Route::controller('runs', 'RunController');
Route::controller('segments', 'SegmentController');
Route::controller('status', 'StatusController');

app/Models/Game.php
<?php

use Illuminate\Database\Eloquent\Model;

class Game extends Model {

    protected $table = 'games';
    protected $fillable = array('name');
    public $timestamps = false;

    public function runs()
    {
        return $this->hasMany('Run');
    }

    public function systems()
    {
        return $this->belongsToMany('System', 'games_systems');
    }

    public function scopeAlphabetized($query)
    {
        return $query->orderBy('name');
    }

    public static function boot()
    {
        parent::boot();

        static::created(function($game)
        {
            //Relate the game and the system it's on after the game is created
            $game->systems()->attach(Input::get('system'));
        });
    }

    public function getAllSegmentsAttribute()
    {
        $segments = 0;

        foreach($this->runs as $run)
        {
            $segments += $run->segments->count();
        }

        return $segments;
    }

    public function getTotalTimePlayedAttribute()
    {
        $time = 0;

        foreach($this->runs as $run)
        {
            foreach($run->segments as $segment)
            {
                $time += Segment::toMilliseconds($segment->time_elapsed);
            }
        }

        return $total = Segment::formatTime($time);
    }

    public static function getTotalTimePlayed()
    {
        $time = 0;

        foreach(Game::all() as $game)
        {
            foreach($game->runs as $run)
            {
                foreach($run->segments as $segment)
                {
                    $time += Segment::toMilliseconds($segment->time_elapsed);
                }
            }
        }

        return $total = Segment::formatTime($time);
    }
}

app/Models/Run.php
<?php

use Illuminate\Database\Eloquent\Model;

class Run extends Model {

    protected $table = 'runs';
    protected $fillable = array('game_id', 'name', 'status_id');
    public $timestamps = false;

    public function game()
    {
        return $this->belongsTo('Game');
    }

    public function segments()
    {
        return $this->hasMany('Segment');
    }

    public function status()
    {
        return $this->belongsTo('Status');
    }

    public function getElapsedTimeAttribute()
    {
        $elapsed = 0;

        foreach($this->segments as $segment)
        {
            $elapsed += Segment::toMilliseconds($segment->time_elapsed);
        }

        return Segment::formatTime($elapsed);
    }

    public function scopeInProgress($query)
    {
        $status = Status::where('status', 'In Progress')->get();

        return $query->where('status_id', $status->first()->id);
    }

    public function scopeCompleted($query)
    {
        $status = Status::where('status', 'Completed')->get();

        return $query->where('status_id', $status->first()->id);
    }

    public function scopeQuit($query)
    {
        $status = Status::where('status', 'Quit')->get();

        return $query->where('status_id', $status->first()->id);
    }

    public function scopeWithoutQuit($query)
    {
        $status = Status::where('status', 'Quit')->get();

        return $query->where('status_id', '!=', $status->first()->id);
    }

    public function scopeGamesPlayed($query)
    {
        return $query->groupBy('game_id');
    }

    public static function boot()
    {
        parent::boot();

        static::creating(function($run)
        {
            $status = Status::where('status', 'In Progress')->get();

            $run->status_id = $status->first()->id;
        });
    }
}

app/Http/Controllers/GameController.php
<?php namespace App\Http\Controllers;

use Illuminate\Routing\Controller;
use App\Http\Requests\CreateGameRequest;
use System, Game;
use Reqest;

class GameController extends Controller
{
    public $data = [];

    public function getAdd()
    {
        $this->data['systems'] = System::lists('name', 'id');

        return response()->json(array('status' => true, 'view' => view('games.modal', $this->data)->render()));
    }

    public function getIndex()
    {
        $this->data['games'] = Game::all();

        return view('games.index', $this->data);
    }

    public function getProfile($gameID)
    {
        $this->data['game'] = Game::find($gameID);

        return view('games.profile', $this->data);
    }

    public function postAdd(CreateGameRequest $request)
    {
        $game = Game::create($request->all());

        return response()->json(array('status' => true, 'game' => $game->toArray(), 'systems' => $game->systems()->first()->toArray(), 'message' => 'Successfully added game to your collection!'));
    }

    public function postAddSystem($gameID)
    {
        $game = Game::find($gameID);
        $game->systems()->attach(Request::get('system_id'));

        return response()->json(array('status' => true));
    }
}

resources/views/games/index.blade.php
@extends('layouts.default')

@section('title', 'GameTimer | Games')

@section('css')
{!! HTML::style('conquer/plugins/data-tables/DT_bootstrap.css') !!}
@stop

@section('page-title')
Game Library
@overwrite

@section('main')
<div class="row">
    <div class="col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">Games</div><div class="pull-right"><a class="btn btn-xs btn-info" id="add_game"><i class="fa fa-plus"></i>  Add Game</a></div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table id="games_table" class="table table-striped table-hover dataTable">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>System</th>
                            <th>Runs</th>
                            <th>Segments</th>
                            <th>Total Time Played</th>
                            <th>Runs Completed</th>
                        </tr>
                        </thead>
                        <tbody id = "game_body">
                        @foreach($games as $game)
                        <tr id="{{$game->id}}">
                            <td><a href="/games/profile/{{$game->id}}">{{$game->name}}</a></td>
                            @if($game->systems->count() > 1)
                                @foreach($game->systems as $system)
                                    <td>{{$system->abbreviation}} </td>
                                @endforeach
                            @else
                                @foreach($game->systems as $system)
                                    <td>{{$system->name}}</td>
                                @endforeach
                            @endif
                            <td>{{$game->runs->count()}}</td>
                            <td>{{$game->all_segments}}</td>
                            <td>{{$game->total_time_played}}</td>
                            <td>{{$game->runs()->completed()->get()->count()}}</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!---Add Game Modal--->
<div id="addModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" aria-hidden="true" data-dismiss="modal" type="button"></button>
                <h4 class="modal-title">Add Game</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="closeModal" class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                <button id="submitModal" class="btn btn-info" type="button">Save</button>
            </div>
        </div>
    </div>
</div>
@stop

@section('jquery2')
{!! HTML::script('conquer/plugins/data-tables/jquery.dataTables.js') !!}
@stop

@section('scripts')
{!! HTML::script('conquer/plugins/data-tables/DT_bootstrap.js') !!}
{!! HTML::script('conquer/js/games.js') !!}
@stop

resources/views/games/modal.blade.php
{!! Form::open() !!}
<div class="row">
    <div class="col-md-12">
        {!! Form::label('name', 'Name') !!}
        {!! Form::text('name', null, array('class' => 'form-control', 'id' => 'name')) !!}
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        {!! Form::label('system', 'System') !!}
        {!! Form::select('system', $systems, null, array('class' => 'form-control', 'id' => 'system')) !!}
    </div>
</div>
{!! Form::close() !!}

resources/views/games/profile.blade.php
@extends('layouts.default')

@section('title', 'GameTimer | Games')

@section('css')
{!! HTML::style('conquer/plugins/data-tables/DT_bootstrap.css') !!}
@stop

@section('page-title')
{{ $game->name }}
@overwrite

@section('main')
<div class="row">
    <div class="col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">Systems</div><div class="pull-right"><a class="btn btn-xs btn-info new_system" id="{{$game->id}}"><i class="fa fa-plus"></i>  New System</a></div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table id="system_table" class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>System</th>
                            <th>Abbreviation</th>
                        </tr>
                        </thead>
                        <tbody id="system_body">
                        @foreach($game->systems as $system)
                        <tr id="{{$system->id}}">
                            <td><a href="/systems/profile/{{$system->id}}">{{$system->name}}</a></td>
                            <td>{{$system->abbreviation}}</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">Runs</div><div class="pull-right"><a class="btn btn-xs btn-info new_run" id="{{$game->id}}"><i class="fa fa-plus"></i>  New Run</a></div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table id="profile_table" class="table table-striped table-hover dataTable">
                        <thead>
                        <tr>
                            <th>Run</th>
                            <th>Segments</th>
                            <th>Time Elapsed</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody id="run_body">
                        @foreach($game->runs as $run)
                        <tr id="{{$run->id}}">
                            <td><a href="/runs/profile/{{$run->id}}">{{$run->name}}</a></td>
                            <td>{{$run->segments->count()}}</td>
                            <td>{{$run->elapsed_time}}</td>
                            <td>{{$run->status->status}}</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!---Add Run Modal--->
<div id="addRunModal" class="modal fade in addModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" aria-hidden="true" data-dismiss="modal" type="button"></button>
                <h4 class="modal-title">New Run</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="closeModal" class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                <button id="submitRunModal" class="btn btn-info" type="button">Save</button>
            </div>
        </div>
    </div>
</div>
<div id="addSysModal" class="modal fade in addModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" aria-hidden="true" data-dismiss="modal" type="button"></button>
                <h4 class="modal-title">New System</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="closeModal" class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                <button id="submitSysModal" class="btn btn-info" type="button">Save</button>
            </div>
        </div>
    </div>
</div>
@stop

@section('jquery2')
{!! HTML::script('conquer/plugins/data-tables/jquery.dataTables.js') !!}
@stop

@section('scripts')
{!! HTML::script('conquer/plugins/data-tables/DT_bootstrap.js') !!}
{!! HTML::script('conquer/js/game-profile.js') !!}
@stop